### ISSUE TITLE
Invalid file error.

### ISSUE THREAD

**Issue by aoshimak** [pebble-dev/rebble-sideloader#13]
I am a maker of language pack. 
I made many language packs in the past, and provide for many years.
They are well works.
But I would open them, "Invalid file" error occurred.
What is the reason of this error?
I need to insert some special message in the header of language packs?

**Comment by AliceGrey** [comment]
Hi @aoshimak. Could you upload a language pack to this github issue that is giving you that error so I can take a look?

**Comment by aoshimak** [comment]
Thank you.
[akt10jp.pbl.zip](https://github.com/pebble-dev/rebble-sideloader/files/5976752/akt10jp.pbl.zip)
[akt10en.pbl.zip](https://github.com/pebble-dev/rebble-sideloader/files/5976753/akt10en.pbl.zip)
[aktmono.pbl.zip](https://github.com/pebble-dev/rebble-sideloader/files/5976754/aktmono.pbl.zip)

**Comment by aoshimak** [comment]
Thank you. I tested Ver1.3. It works fine with Japanese message display.
