### ISSUE TITLE
Button text low-contrast display bug

### ISSUE THREAD

**Issue by bmacphail** [pebble-dev/rebble-sideloader#14]
Is it just me, or does the text here look a little too bright for the background on this button?
![Screenshot_20210220-141743_Sideloader](https://user-images.githubusercontent.com/12399661/108610006-01a06480-7387-11eb-85aa-5be4985159a5.jpg)

I am on a Samsung S9 running Android 10 with system dark mode enabled.

**Comment by AliceGrey** [comment]
@piggehperson Do you have any input on what color we should change the button text to?
